server:
  port: 8081

spring:
  application:
    name: ms-finance
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/financeos}
    username: ${SPRING_DATASOURCE_USERNAME:financeos_user}
    password: ${SPRING_DATASOURCE_PASSWORD:financeos_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.financeos: DEBUG
